package cy.cav.framework;

import jakarta.annotation.*;

import java.time.*;
import java.util.*;

/// Holds a [Message] with additional data: the sender, the receiver, and time info.
///
/// This is what gets sent on the wire in HTTP REST communications.
///
/// @param <T>       the type of the message contained in the envelope
/// @param sender    the actor or server who sent the message
/// @param receiver  the actor who should receive the message; in cases of responses, it's a server address
/// @param requestId for synchronous requests, stores the id of the request-response transaction, generated by the sender; otherwise, is 0
/// @param body      the data of the message
/// @param sentAt    the time at which the message has been sent
public record Envelope<T extends Message>(
        ActorAddress sender,
        ActorAddress receiver,
        long requestId,
        T body,
        Instant sentAt
) {
    public Envelope {
        Objects.requireNonNull(body, "Body must not be null!");
        Objects.requireNonNull(sender, "Sender must not be null!");
        Objects.requireNonNull(receiver, "Receiver must not be null!");
        Objects.requireNonNull(sentAt, "Sent at must not be null!");

        if (receiver.isServerAddress() && requestId == 0) {
            throw new IllegalArgumentException("Can't send a message to the server without a request id!");
        }

        if (requestId != 0 && !(body instanceof Message.Request<?> || body instanceof Message.Response)) {
            throw new IllegalArgumentException("A sync envelope must have either a Request or a Response");
        }

        if (requestId == 0 && !(body instanceof Message.Notification || body instanceof Message.Request<?>)) {
            throw new IllegalArgumentException("An async envelope must have either a Notification or a Request.");
        }
    }
}
