package cy.cav.framework;

import jakarta.annotation.*;

import java.time.*;
import java.util.*;

/// Holds a [Message] with additional data: the sender, the receiver, and time info.
///
/// This is what gets sent on the wire in HTTP REST communications.
///
/// @param sender          the actor who sent the message; can be null
/// @param receiver        the actor who should receive the message; in cases of responses, can be a server address
/// @param requestId       for synchronous requests, stores the id of the request-response transaction, generated by the sender; otherwise, is 0
/// @param body            the data of the message
/// @param sentAt          the time at which the message has been sent
public record Envelope(
        @Nullable ActorAddress sender,
        ActorAddress receiver,
        long requestId,
        Message body,
        Instant sentAt
) {
    public Envelope {
        Objects.requireNonNull(body, "Body must not be null!");
        Objects.requireNonNull(receiver, "Receiver must not be null!");
        Objects.requireNonNull(sentAt, "Sent at must not be null!");

        if (receiver.isServerAddress() && requestId == 0) {
            throw new IllegalArgumentException("Can't send a message to the server without a request id!");
        }
    }
}
